Repository JamezDon/Group-Project-Advanced-Data-Week-5, pull requests merged in 2025-06, with the labels that each got.

#65 #39-create-dashboard-template
  dashboard/main.py
  dashboard/pages/1_current_data.py
  dashboard/pages/2_long_term_data.py
  dashboard/requirements.txt
Labels: enhancement

#81 Add terraform for s3 bucket and ECRs.
  pipeline/terraform/main.tf
Labels: s3

#79 70 40 enhancement dockerise script ready for Lambda
  .github/workflows/lint.yml
  old_data/metadata_to_s3/dockerfile
  old_data/metadata_to_s3/extract.py
  old_data/metadata_to_s3/load.py
  old_data/metadata_to_s3/main.py
  old_data/metadata_to_s3/metadata_pipeline_lambda.py
  old_data/metadata_to_s3/test_pipeline.py
  old_data/metadata_to_s3/transform.py
  old_data/sensor_reading_to_s3/dockerfile
  old_data/sensor_reading_to_s3/extract.py
  old_data/sensor_reading_to_s3/load.py
  old_data/sensor_reading_to_s3/main.py
  old_data/sensor_reading_to_s3/sensor_reading_pipeline_lambda.py
  old_data/sensor_reading_to_s3/test_extract.py
  old_data/sensor_reading_to_s3/transform.py
  pipeline/connect.sh
Labels: enhancement, s3
